### ISSUE TITLE
GitHub button behavior

### ISSUE THREAD

**Issue by enetz** [OpenMS/openms.de#46] opened 2022-07-21 14:19 UTC
I mentioned this before on a longer list of small issues, but this is something that bothers me a lot when it happens on other websites:
buttons that don't show the linked destination and can't be opened in a new tab or window.
This works well for most of the website, including the OpenMS logo on the top.
As far as I can see, this only applies to the GitHub buttons on the applications page.

What is the trade-off here, is it required for the mouse-over color change? Is that worth the annoyance?
It combines two issues:
1. it looks untrustworthy: you don't know where you end up, before clicking on it and loading the target page. GitHub won't give you viruses, but a new visitor to the website can't confirm the link actually goes there, before loading the page.
2. Usability: I personally don't like to open links to external websites on the same tab. Especially if you are just exploring, you would open it in a new tab, look and click around on GitHub, then close it. Having to duplicate the page first, or backtracking all the way back to the homepage after clicking around on GitHub is annoying.

**Comment by rahul799** [comment] 2022-07-27 10:05
Hi @enetz,
Thankyou for pointing it out and sorry for the delay. 
I have made the changes. Can you please review?

**Comment by enetz** [comment] 2022-07-27 17:40
if I am looking in the right place, I see that it now opens the link in a new tab. this fixes the 2. issue, but not the 1.

I am open to other opinions, but showing the destination of a link in the bottom left corner is a basic feature of every modern browser and I myself use it a lot. Links or Buttons that don't do that should be reserved for navigation within the website, like the list on the left side of Applications. Outgoing links should tell you the destination before you click on them.

**Comment by jpfeuffer** [comment] 2022-07-27 17:58
@rahul799 why not just style the link as button? Then we also save the JS calls

**Comment by rahul799** [comment] 2022-08-11 06:46
Thankyou for suggestions @jpfeuffer . The issue is fixed now. @enetz can we close this issue?

**Closed** 2022-08-15 12:52 UTC
